# This workflow is managed by gh actions-lock.

name: Deploy Theme
on:
  push:
    branches:
      - customized
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    permissions:
      contents: read
      
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            nodejs.org:443
            registry.yarnpkg.com:443
            repo.yarnpkg.com:443
            scrumbug.ghost.io:443
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
      - run: corepack enable
      - run: |
          yarn install
          yarn zip
      - uses: tryghost/action-deploy-theme@v2.0.3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
