name: Deploy Theme
on:
  push:
    branches:
      - customized
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: |
          yarn install
          yarn zip
      - uses: TryGhost/action-deploy-theme@ba1de75b3eef27fee07a4cab741d27d179c198d8 # v1.6.4
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
